export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<div>2312</div>
			<body>{children}</body>
		</html>
	);
}
